### ISSUE TITLE
 Consumer swallows all messages but the last one

### ISSUE THREAD

**Issue by mlively** [php-enqueue/gearman#1]
When consuming messages, the GearmanConsumer will eat all of the messages but only return the last one. Because of the interface of the Interop\Queue\Consumer only accepting a single message, it probably makes more sense to just run $this->worker->work() once instead of twice. 

A PR is incoming.

**Comment by makasim** [comment]
fixed in https://github.com/php-enqueue/enqueue-dev/pull/998
